# Generated by Django 4.2.6 on 2023-10-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_alter_funcionario_empresa'),
        ('documentos', '0002_documento_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
        ),
    ]
